channels_on = [
    # Main channels
    "gra-u-szadka",
    "testy",
    "DD 3e",
    "ZEW",
    "WARHAMMER",
    "GRA",
    "CYKLE",
    "DCC",
    "OSE",
    "jednostrzały",
    "DD 5e",
    "CYBERPUNKRED",
    "Sesja publiczna",
    "SESJA PUBLICZNA",
    "generau-czat",
    "DELTA GREEN",
    "Mothership",
    "Traveller",
    "cp",
    "dd",
    # DPS Channels
    "Off",
    "Tomas_DPS",
    "Basia_DPS",
    "Mirko",
    "Inne",
    "Paqul",
    "Kot",
    "Stream",
    "dyskusje",
    "Coen",
    "Naiya",
    "Wbear",
    "Shadow",
    # END OF DPS Channels
    # COENCAVE Channels
    "Sesja-Coena",
    "Pogaduszki",
    "grane-w-gre",
    # END OF COENCAVE Channels
    # Additional channels from previous config
    "Tajemnice Pętli",
    "Never going home",
    "Delta Green",
    "Słowianie",
    "Warhammer",
]
channels_on_test = ["sala_spotkań", "dział_techcznicny", "general"]